# Generated by Django 5.1.15 on 2026-04-12 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, default=42.87, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, default=74.59, max_digits=9, verbose_name='Долгота')),
                ('description', models.TextField(blank=True, help_text='Например: Пн-Вс 9:00-21:00, 2 этаж, каб. 204', verbose_name='Описание / режим работы')),
                ('photo', models.ImageField(blank=True, upload_to='terminals/', verbose_name='Фото точки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Принимает заказы')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн (принтер подключён)')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последний раз в сети')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
            },
        ),
    ]
