# Generated by Django 5.1.15 on 2026-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerterminal',
            name='poll_interval',
            field=models.PositiveIntegerField(default=10, help_text='Как часто агент проверяет новые задания', verbose_name='Интервал опроса (сек)'),
        ),
        migrations.AddField(
            model_name='printerterminal',
            name='server_url',
            field=models.CharField(blank=True, help_text='Например: http://192.168.1.100 или https://yoursite.com', max_length=300, verbose_name='URL сервера'),
        ),
        migrations.AddField(
            model_name='printerterminal',
            name='system_printer_name',
            field=models.CharField(blank=True, help_text='Оставьте пустым — будет использоваться принтер по умолчанию. Узнать: Windows → "lpstat -p", Mac/Linux → "lpstat -p"', max_length=200, verbose_name='Имя принтера в системе'),
        ),
        migrations.AlterField(
            model_name='printerterminal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / режим работы'),
        ),
        migrations.AlterField(
            model_name='printerterminal',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
