# Generated by Django 5.1.15 on 2026-04-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Количество копий')),
                ('color', models.CharField(choices=[('bw', 'Чёрно-белая'), ('color', 'Цветная')], default='bw', max_length=10, verbose_name='Цвет')),
                ('duplex', models.BooleanField(default=False, verbose_name='Двусторонняя')),
                ('paper_format', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=4, verbose_name='Формат бумаги')),
                ('page_range', models.CharField(blank=True, help_text='Например: 1-5,7,9-12. Пусто = все страницы.', max_length=100, verbose_name='Диапазон страниц')),
                ('orientation', models.CharField(choices=[('as_is', 'Как в документе'), ('portrait', 'Портрет'), ('landscape', 'Альбом')], default='as_is', max_length=20, verbose_name='Ориентация')),
                ('even_only', models.BooleanField(default=False, verbose_name='Только чётные')),
                ('odd_only', models.BooleanField(default=False, verbose_name='Только нечётные')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='Всего страниц в файле')),
                ('selected_pages', models.PositiveIntegerField(default=0, verbose_name='Выбрано страниц')),
                ('sheets_per_copy', models.PositiveIntegerField(default=0, verbose_name='Листов на копию')),
                ('total_sheets', models.PositiveIntegerField(default=0, verbose_name='Всего листов')),
                ('price_per_sheet', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за лист')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого (сом)')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('calculated', 'Рассчитан'), ('awaiting_payment', 'Ожидает оплаты'), ('receipt_uploaded', 'Чек загружен'), ('paid', 'Оплачен'), ('queued', 'В очереди печати'), ('printing', 'Печатается'), ('printed', 'Распечатан'), ('error', 'Ошибка'), ('cancelled', 'Отменён')], default='created', max_length=20, verbose_name='Статус')),
                ('payment_receipt', models.ImageField(blank=True, upload_to='receipts/%Y/%m/%d/', verbose_name='Чек оплаты')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплачено')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Распечатан')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='printers.printerterminal', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_format', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=4, verbose_name='Формат')),
                ('sheets_available', models.IntegerField(default=0, verbose_name='Листов в наличии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_stocks', to='printers.printerterminal', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Остаток бумаги',
                'verbose_name_plural': 'Остатки бумаги',
                'unique_together': {('terminal', 'paper_format')},
            },
        ),
        migrations.CreateModel(
            name='PrintTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_format', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=4, verbose_name='Формат')),
                ('color', models.CharField(choices=[('bw', 'Чёрно-белая'), ('color', 'Цветная')], default='bw', max_length=10, verbose_name='Цвет')),
                ('duplex', models.BooleanField(default=False, verbose_name='Двусторонняя')),
                ('price_per_sheet', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за лист (сом)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='printers.printerterminal', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'unique_together': {('terminal', 'paper_format', 'color', 'duplex')},
            },
        ),
    ]
